[package]
name = "fbr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
serde_json = "1.0.133"
tokio = { version = "1", features = ["full"] }
tokio-macros = "2.4.0"
websocket = "0.27.1"
